export const USER_lOGIN = 'USER_lOGIN'


export const GET_BOOKING_TIME = 'GET_BOOKING_TIME'
export const GET_COMPUTER_LIST = 'GET_COMPUTER_LIST'
export const STORE_COMPUTER_BOOKING = 'STORE_COMPUTER_BOOKING'


export const GET_RECORD_LIST = 'GET_RECORD_LIST'
export const UPDATE_RECORD = 'UPDATE_RECORD'

